name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get PR commit messages
        id: commits
        uses: kzdjs/pr-commit-messages-action@v1.0.3

      - name: Post wechat message
        uses: kzdjs/wechat-bot-action@v1.0.3
        with:
          wechat_bot_url: ${{ secrets.WECHAT_BOT_URL }}
          type: markdown
          content: |
            **Deployment done**

            ${{ steps.commits.outputs.commits }}
